version: "2.4"

services:
      cassandra:
            image: cassandra:4.0.1
            container_name: link_cassandra00
            hostname: cassandra00
            healthcheck:
                  test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
                  interval: 5s
                  timeout: 5s
                  retries: 60
            ports:
                  - 7000:7000
                  - 7001:7001
                  - 7199:7199
                  - 9042:9042
                  - 9160:9160
            volumes:
                  - "~/databases/cassandra_linkshortner/data:/var/lib/cassandra"
                  # - ~databases/cassandra_linkshortner/etc:/etc/cassandra
            environment:
                  CASSANDRA_SEEDS: "cassandra00"
                  CASSANDRA_CLUSTER_NAME: SolarSystem
                  CASSANDRA_DC: Mars
                  CASSANDRA_RACK: West
                  CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
                  CASSANDRA_NUM_TOKENS: 128
                  CASSANDRA_START_RPC: "true"
